[versions]
appName = "My Resume"
appNamespaceId = "mughalasim.my.cv"
appVersionCode = "13"
appVersionName = "13.0"
compileSdk = "34"
minSdk = "24"
accompanist = "0.32.0"
activity-compose = "1.9.0"
android-joda = "2.10.3"
androidx-junit = "1.1.5"
annotation-jvm = "1.7.1"
appcompat = "1.6.1"
applocale = "3.1.0"
arrow-core = "1.0.1"
compiler = "1.5.13"
compose = "1.6.7"
core-ktx = "1.13.1"
coroutines = "1.8.0"
espresso = "3.5.1"
junit = "4.13.2"
koin-android = "3.5.3"
koin-androidx-compose = "3.4.6"
kotlin-reflect = "1.9.22"
lifecycle = "2.7.0"
lifecycle-extensions = "2.2.0"
navigation-compose = "2.7.5"
restring = "5.2.2"
reword = "4.0.4"
viewpump = "4.0.10"
spotless = "6.25.0"
detekt = "1.23.5"

[libraries]
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
android-joda = { module = "net.danlew:android.joda", version.ref = "android-joda" }
annotation-jvm = { module = "androidx.annotation:annotation-jvm", version.ref = "annotation-jvm" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
applocale = { module = "dev.b3nedikt.applocale:applocale", version.ref = "applocale" }
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow-core" }
compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compiler" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
foundation-android = { module = "androidx.compose.foundation:foundation-android", version.ref = "compose" }
junit = { module = "junit:junit", version.ref = "junit" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin-android" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin-androidx-compose" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin-reflect" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycle-extensions" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
material = { module = "androidx.compose.material:material", version.ref = "compose" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
restring = { module = "dev.b3nedikt.restring:restring", version.ref = "restring" }
reword = { module = "dev.b3nedikt.reword:reword", version.ref = "reword" }
runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose" }
ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
viewpump = { module = "dev.b3nedikt.viewpump:viewpump", version.ref = "viewpump" }

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }