[versions]
appName = "My Resume"
appNamespaceId = "mughalasim.my.cv"
appVersionCode = "16"
appVersionName = "16.0"
appCompileSdk = "34"
appTargetSdk = "34"
appMinSdk = "24"
materialIconsExtendedAndroid = "1.7.3"
coilCompose = "2.6.0"
firebaseBom = "33.4.0"
kotlinxSerializationJson = "1.6.3"
accompanist = "0.32.0"
activity-compose = "1.9.2"
android-joda = "2.12.7"
annotation-jvm = "1.8.2"
appcompat = "1.7.0"
applocale = "3.1.0"
compiler = "1.5.15"
compose = "1.7.3"
core-ktx = "1.13.1"
coroutines = "1.8.0"
junit = "4.13.2"
koin-android = "3.5.3"
kotlin-reflect = "1.9.22"
lifecycle = "2.8.6"
lifecycle-extensions = "2.2.0"
navigation-compose = "2.8.2"
okhttpBom = "4.12.0"
restring = "5.2.2"
retrofit = "2.11.0"
retrofit2KotlinxSerializationConverter = "1.0.0"
reword = "4.0.4"
viewpump = "4.0.10"
spotless = "6.25.0"
detekt = "1.23.5"
kotlin = "2.0.0"
androidGradlePlugin = "8.4.2"
google = "4.4.2"
crashlytics = "3.0.2"
material3Android = "1.3.0"

[libraries]
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
android-joda = { module = "net.danlew:android.joda", version.ref = "android-joda" }
annotation-jvm = { module = "androidx.annotation:annotation-jvm", version.ref = "annotation-jvm" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
applocale = { module = "dev.b3nedikt.applocale:applocale", version.ref = "applocale" }
compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compiler" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-database = { module = "com.google.firebase:firebase-database" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
foundation-android = { module = "androidx.compose.foundation:foundation-android", version.ref = "compose" }
junit = { module = "junit:junit", version.ref = "junit" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin-android" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin-android" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin-android" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin-reflect" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycle-extensions" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "lifecycle" }
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor" }
material-icons-extended-android = { module = "androidx.compose.material:material-icons-extended-android", version.ref = "materialIconsExtendedAndroid" }
material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3Android" }
material = { module = "androidx.compose.material:material", version.ref = "compose" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
okhttp-bom = { group = "com.squareup.okhttp3", name = "okhttp-bom", version.ref = "okhttpBom" }
okhttp = { module = "com.squareup.okhttp3:okhttp" }
restring = { module = "dev.b3nedikt.restring:restring", version.ref = "restring" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit2-kotlinx-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit2KotlinxSerializationConverter" }
reword = { module = "dev.b3nedikt.reword:reword", version.ref = "reword" }
runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
viewpump = { module = "dev.b3nedikt.viewpump:viewpump", version.ref = "viewpump" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
google-services = { id = "com.google.gms.google-services", version.ref = "google" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }